// homelab/hosts/rpi/webapp.v3.Fable/frontend/src/lib/components/Modal.svelte
<script lang="ts">
  import { Dialog } from 'bits-ui';
  import { X } from '@lucide/svelte';
  import type { Snippet } from 'svelte';

  let {
    open = $bindable(false),
    title,
    wide = false,
    onclose,
    children,
    actions,
  }: {
    open?: boolean;
    title: string;
    wide?: boolean;
    onclose?: () => void;
    children?: Snippet;
    actions?: Snippet;
  } = $props();
</script>

<Dialog.Root bind:open onOpenChange={(v) => { if (!v) onclose?.(); }}>
  <Dialog.Portal>
    <Dialog.Overlay class="modal-overlay" />
    <Dialog.Content class="modal {wide ? 'wide' : ''}">
      <div class="modal-head">
        <Dialog.Title class="modal-title">{title}</Dialog.Title>
        {#if actions}{@render actions()}{/if}
        <Dialog.Close class="tbtn icon" aria-label="Close"><X /></Dialog.Close>
      </div>
      <div class="modal-body">
        {@render children?.()}
      </div>
    </Dialog.Content>
  </Dialog.Portal>
</Dialog.Root>

// homelab/hosts/rpi/webapp/frontend/src/components/Modal.tsx
import * as Dialog from '@radix-ui/react-dialog';
import { X } from 'lucide-react';
import type { ReactNode } from 'react';

export function Modal({
  open, onClose, title, children, wide,
}: {
  open: boolean;
  onClose: () => void;
  title: ReactNode;
  children: ReactNode;
  wide?: boolean;
}) {
  return (
    <Dialog.Root open={open} onOpenChange={(o) => { if (!o) onClose(); }}>
      <Dialog.Portal>
        <Dialog.Overlay className="modal-overlay" />
        <Dialog.Content className={`modal glass-strong${wide ? ' modal-wide' : ''}`}>
          <div className="modal-head">
            <Dialog.Title className="modal-title">{title}</Dialog.Title>
            <Dialog.Close asChild>
              <button className="tb-btn" aria-label="Close"><X /></button>
            </Dialog.Close>
          </div>
          <div className="modal-body">{children}</div>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  );
}
