// homelab/hosts/rpi/webapp.v3.Astra/frontend/src/components/LogTail.tsx
// Live log drawer for a runner. The dispatcher already writes <name>.log next to
// the reports; this polls the tail while it's open, so "Run now" shows progress
// instead of a 90-second silence.
import { useEffect, useRef } from 'react';
import { useQuery } from '@tanstack/react-query';
import { get } from '../lib/api';
import { relTime } from '../lib/format';
import { Modal } from './Modal';

interface LogResp {
  name: string;
  exists: boolean;
  lines: string[];
  mtime?: string;
  size: number;
}

export function LogTail({ name, label, onClose }: { name: string; label: string; onClose: () => void }) {
  const bottom = useRef<HTMLDivElement>(null);

  const q = useQuery({
    queryKey: ['runner-log', name],
    queryFn: () => get<LogResp>(`/api/runners/${name}/log?lines=300`, 15_000),
    refetchInterval: 3000,
  });

  useEffect(() => { bottom.current?.scrollIntoView({ block: 'end' }); }, [q.dataUpdatedAt]);

  return (
    <Modal open onClose={onClose} title={`${label} — live log`} wide>
      {q.data && !q.data.exists && (
        <p className="t-dim">
          No log file for this runner yet. It writes one on its next run; the report
          itself updates either way.
        </p>
      )}
      {q.data?.exists && (
        <>
          <div className="t-dim log-meta">
            {(q.data.size / 1024).toFixed(1)} KB · updated {relTime(q.data.mtime)} · polling every 3s
          </div>
          <pre className="log-tail mono">
            {q.data.lines.join('\n')}
            <div ref={bottom} />
          </pre>
        </>
      )}
    </Modal>
  );
}

// homelab/hosts/opti/apps/webapp.v3.Fable/frontend/src/lib/components/LogTail.svelte
<script lang="ts">
  // Live log drawer for a runner. The dispatcher already writes <name>.log next to
  // the reports; this polls the tail while it's open, so "Run now" shows progress
  // instead of a 90-second silence.
  import { createQuery } from '@tanstack/svelte-query';
  import Modal from './Modal.svelte';
  import { get } from '$lib/api/client';
  import { relTime } from '$lib/format';

  interface LogResp { name: string; exists: boolean; lines: string[]; mtime?: string; size: number }

  let { name, label, onclose }: { name: string; label: string; onclose: () => void } = $props();

  const q = createQuery(() => ({
    queryKey: ['runner-log', name],
    queryFn: () => get<LogResp>(`/api/runners/${name}/log?lines=300`, 15_000),
    refetchInterval: 3000,
  }));

  let pre: HTMLPreElement | undefined = $state();
  $effect(() => {
    q.dataUpdatedAt;
    if (pre) pre.scrollTop = pre.scrollHeight;
  });
</script>

<Modal open title="{label} — live log" wide {onclose}>
  {#if q.isError}
    <p class="err">Could not read the log — {(q.error as Error).message}</p>
  {:else if q.data && !q.data.exists}
    <p class="dim">No log file for this runner yet. It writes one on its next run; the report itself updates either way.</p>
  {:else if q.data?.exists}
    <div class="log-meta">{(q.data.size / 1024).toFixed(1)} KB · updated {relTime(q.data.mtime)} · polling every 3s</div>
    <pre class="log-tail" bind:this={pre}>{q.data.lines.join('\n')}</pre>
  {:else}
    <div class="spin"></div>
  {/if}
</Modal>
