// homelab/hosts/rpi/webapp.v2.legacy/frontend/src/board/BoardGrid.tsx
// The board: a responsive react-grid-layout whose serialized layout IS the
// persisted document ({i,x,y,w,h} per breakpoint). Drag/resize are enabled only
// in edit mode, so a normal visit can't nudge the layout.
//
// RGL v2 notes (it differs from every v1 example on the web):
//   - neither responsive helper worked for this board: <ResponsiveGridLayout>
//     ignored the `cols`/`breakpoints` props (a 12-column board rendered in 4
//     columns), and useResponsiveLayout() kept its mount-time breakpoint when the
//     window was resized. Breakpoint selection is nine lines, so it lives here
//     and a plain <GridLayout> does the rendering.
//   - there is no WidthProvider; width is measured below. The library's
//     useContainerWidth() did not follow the container across a viewport change
//     (verified 2026-08-11: a phone-width window kept the desktop grid width).
//   - drag/resize are configured with dragConfig/resizeConfig objects, not the
//     v1 isDraggable/isResizable/draggableCancel props.
import { useEffect, useRef, useState } from 'react';
import {
  GridLayout, verticalCompactor,
  type Layout, type LayoutItem, type ResponsiveLayouts,
} from 'react-grid-layout';
import { Settings2, X } from 'lucide-react';
import type { BoardDoc, WidgetInstance } from '../lib/api-types';
import { WIDGET_BY_TYPE } from '../widgets/registry';
import { WidgetCtx } from './widget-ctx';
import { WidgetError } from '../widgets/kit';

// Exactly two breakpoints, matching the two layouts a board document stores.
// A third (md) was worse than useless: boards carry no md geometry, so it fell
// back to the 12-column lg coordinates, clamped every x into 8 columns, and
// compaction then stacked the whole board into one column on a normal laptop.
const COLS = { lg: 12, sm: 2 };
const BREAKPOINTS = { lg: 760, sm: 0 };
const ROW_HEIGHT = 62;
const MARGIN: [number, number] = [12, 12];

function useMeasuredWidth() {
  const ref = useRef<HTMLDivElement>(null);
  const [width, setWidth] = useState(0);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const apply = () => setWidth(el.getBoundingClientRect().width);
    apply();
    const ro = new ResizeObserver(apply);
    ro.observe(el);
    window.addEventListener('resize', apply);
    return () => { ro.disconnect(); window.removeEventListener('resize', apply); };
  }, []);

  return { ref, width };
}

function WidgetHost({
  widget, onOptionsChange,
}: {
  widget: WidgetInstance;
  onOptionsChange: (id: string, options: Record<string, unknown>) => void;
}) {
  const def = WIDGET_BY_TYPE[widget.type];
  if (!def) {
    return (
      <div className="w-card glass">
        <WidgetError message={`unknown widget type '${widget.type}'`} />
      </div>
    );
  }
  const Component = def.component;
  return (
    <WidgetCtx.Provider value={{ updateOptions: (options) => onOptionsChange(widget.id, options) }}>
      <Component options={widget.options} />
    </WidgetCtx.Provider>
  );
}

export function BoardGrid({
  board, editMode, onLayoutChange, onRemove, onConfigure, onOptionsChange,
}: {
  board: BoardDoc;
  editMode: boolean;
  onLayoutChange: (layouts: ResponsiveLayouts) => void;
  onRemove: (id: string) => void;
  onConfigure: (id: string) => void;
  onOptionsChange: (id: string, options: Record<string, unknown>) => void;
}) {
  const { ref, width } = useMeasuredWidth();

  // A widget with no layout entry (added at another breakpoint, or a preset that
  // predates it) still has to render — give it a default-sized slot at the end.
  const layouts: ResponsiveLayouts = {};
  for (const bp of Object.keys(COLS) as (keyof typeof COLS)[]) {
    const existing = board.layouts[bp] ?? board.layouts.lg ?? [];
    const byId = new Map(existing.map((l) => [l.i, l]));
    layouts[bp] = board.widgets.map((w, idx): LayoutItem => {
      const def = WIDGET_BY_TYPE[w.type];
      const found = byId.get(w.id);
      const minW = def?.min?.w != null ? Math.min(def.min.w, COLS[bp]) : undefined;
      if (found) return { ...found, w: Math.min(found.w, COLS[bp]), minW, minH: def?.min?.h };
      return {
        i: w.id,
        x: 0,
        y: 1000 + idx,
        w: Math.min(def?.defaults.w ?? 4, COLS[bp]),
        h: def?.defaults.h ?? 3,
        minW,
        minH: def?.min?.h,
      };
    });
  }

  // Largest breakpoint whose min-width the measured container clears.
  const bp = (Object.keys(BREAKPOINTS) as (keyof typeof COLS)[])
    .sort((a, b) => BREAKPOINTS[b] - BREAKPOINTS[a])
    .find((k) => width >= BREAKPOINTS[k]) ?? 'sm';

  const handleLayoutChange = (layout: Layout) => {
    if (!editMode) return;
    // Write back only the breakpoint being edited; the other keeps its own geometry.
    onLayoutChange({ ...layouts, [bp]: layout });
  };

  return (
    <div ref={ref}>
      {width > 0 && (
        <GridLayout
          className={`board${editMode ? ' editing' : ''}`}
          width={width}
          layout={layouts[bp]}
          gridConfig={{
            cols: COLS[bp],
            rowHeight: ROW_HEIGHT,
            margin: MARGIN,
            containerPadding: [0, 0],
          }}
          compactor={verticalCompactor}
          dragConfig={{ enabled: editMode, cancel: '.w-actions,button,a,input,select,textarea' }}
          resizeConfig={{ enabled: editMode }}
          onLayoutChange={handleLayoutChange}
        >
          {board.widgets.map((w) => (
            <div key={w.id} className="board-item">
              {editMode && (
                <div className="w-edit-bar">
                  <button className="w-edit-btn" title="Configure" onClick={() => onConfigure(w.id)}><Settings2 /></button>
                  <button className="w-edit-btn danger" title="Remove" onClick={() => onRemove(w.id)}><X /></button>
                </div>
              )}
              <WidgetHost widget={w} onOptionsChange={onOptionsChange} />
            </div>
          ))}
        </GridLayout>
      )}
    </div>
  );
}

// homelab/hosts/rpi/webapp.v3.Fable/frontend/src/lib/board/BoardGrid.svelte
<script lang="ts">
  // The board: gridstack owns positions, Svelte owns the DOM inside each item. The
  // persisted document ({i,x,y,w,h} per breakpoint) is the source of truth — this
  // component maps it onto gridstack nodes and reads it back on change.
  //
  // Exactly two breakpoints, matching the two layouts a board document stores
  // (lg = 12 columns, sm = 2 columns). Breakpoint selection is measured here,
  // not delegated to gridstack's responsive mode, because gridstack would compute
  // its own sm layout instead of loading the one the document carries.
  //
  // Drag/resize only in edit mode (static grid otherwise), so a normal visit can't
  // nudge the layout.
  import { onMount } from 'svelte';
  import { GridStack, type GridItemHTMLElement, type GridStackNode } from 'gridstack';
  import { Settings2, X } from '@lucide/svelte';
  import type { BoardDoc, GridItem } from '$lib/api/types';
  import { WIDGET_BY_TYPE } from '$lib/widgets/registry';
  import WidgetHost from './WidgetHost.svelte';

  type Bp = 'lg' | 'sm';
  const COLS: Record<Bp, number> = { lg: 12, sm: 2 };
  const BREAK = 760;
  const ROW_HEIGHT = 62;
  const MARGIN = 12;

  let {
    board,
    editMode = false,
    onLayoutChange,
    onRemove,
    onConfigure,
    onOptionsChange,
  }: {
    board: BoardDoc;
    editMode?: boolean;
    onLayoutChange: (layouts: Record<string, GridItem[]>) => void;
    onRemove: (id: string) => void;
    onConfigure: (id: string) => void;
    onOptionsChange: (id: string, options: Record<string, unknown>) => void;
  } = $props();

  let host: HTMLDivElement;
  let gridEl: HTMLDivElement;
  let grid: GridStack | null = null;
  let bp: Bp = 'lg';
  let applying = false;
  const items = new Map<string, GridItemHTMLElement>();
  const pending: GridItemHTMLElement[] = [];

  // A widget with no layout entry (added at another breakpoint, or a preset that
  // predates it) still has to render — give it a default-sized slot at the end.
  function nodeFor(id: string, b: Bp) {
    const inst = board.widgets.find((x) => x.id === id);
    const def = inst ? WIDGET_BY_TYPE[inst.type] : undefined;
    const existing = board.layouts[b] ?? board.layouts.lg ?? [];
    const found = existing.find((l) => l.i === id);
    const cols = COLS[b];
    // Registry minimums describe the 12-column grid. Never let them exceed the
    // stored size, or a stat tile saved at w:1 on the 2-column layout gets widened
    // to its lg minimum and every neighbour re-stacks beneath it.
    const w = found ? Math.min(found.w, cols) : Math.min(def?.defaults.w ?? 4, cols);
    const h = found ? found.h : (def?.defaults.h ?? 3);
    const minW = def?.min?.w != null ? Math.min(def.min.w, cols, w) : undefined;
    const minH = def?.min?.h != null ? Math.min(def.min.h, h) : undefined;
    if (found) return { id, x: Math.min(found.x, cols - w), y: found.y, w, h, minW, minH };
    const idx = board.widgets.findIndex((x) => x.id === id);
    return { id, x: 0, y: 1000 + idx, w, h, minW, minH };
  }

  function register(el: GridItemHTMLElement) {
    const id = el.dataset.id!;
    items.set(id, el);
    if (!grid) { pending.push(el); return; }
    applying = true;
    grid.makeWidget(el, nodeFor(id, bp));
    applying = false;
  }
  function unregister(el: GridItemHTMLElement) {
    items.delete(el.dataset.id!);
    if (grid && el.gridstackNode) grid.removeWidget(el, false, false);
  }
  function gridItem(el: HTMLElement) {
    register(el as GridItemHTMLElement);
    return { destroy() { unregister(el as GridItemHTMLElement); } };
  }

  function applyLayout() {
    if (!grid) return;
    applying = true;
    grid.batchUpdate();
    for (const [id, el] of items) grid.update(el, nodeFor(id, bp));
    grid.batchUpdate(false);
    applying = false;
  }

  function readLayout(): GridItem[] {
    return (grid!.save(false) as GridStackNode[]).map((n) => ({
      i: String(n.id), x: n.x ?? 0, y: n.y ?? 0, w: n.w ?? 1, h: n.h ?? 1,
    }));
  }

  function bpFor(width: number): Bp { return width >= BREAK ? 'lg' : 'sm'; }

  onMount(() => {
    bp = bpFor(host.getBoundingClientRect().width);
    grid = GridStack.init({
      column: COLS[bp],
      cellHeight: ROW_HEIGHT,
      margin: MARGIN,
      float: false,
      animate: true,
      auto: false,
      staticGrid: !editMode,
      alwaysShowResizeHandle: 'mobile',
      draggable: { cancel: '.w-actions,.w-edit-bar,button,a,input,select,textarea,.spark-box' },
      resizable: { handles: 'se' },
    }, gridEl)!;
    grid.batchUpdate();
    for (const el of pending.splice(0)) grid.makeWidget(el, nodeFor(el.dataset.id!, bp));
    grid.batchUpdate(false);

    grid.on('change', () => {
      if (applying || !editMode || !grid || grid.isIgnoreChangeCB()) return;
      // Write back only the breakpoint being edited; the other keeps its own geometry.
      onLayoutChange({ ...board.layouts, [bp]: readLayout() });
    });

    const ro = new ResizeObserver(() => {
      const next = bpFor(host.getBoundingClientRect().width);
      if (next !== bp && grid) {
        bp = next;
        applying = true;
        grid.column(COLS[bp], 'none');
        applying = false;
        applyLayout();
      }
    });
    ro.observe(host);

    return () => { ro.disconnect(); grid?.destroy(false); grid = null; };
  });

  $effect(() => { grid?.setStatic(!editMode); });

  // External layout changes (reload, 409 recovery, a widget added) re-apply the
  // document. The stringify guard keeps a drag's own write-back from bouncing.
  let lastApplied = '';
  $effect(() => {
    const key = JSON.stringify(board.layouts);
    if (key !== lastApplied) {
      lastApplied = key;
      if (grid) applyLayout();
    }
  });
</script>

<div bind:this={host} class="board-host">
  <div class="grid-stack board" class:editing={editMode} bind:this={gridEl}>
    {#each board.widgets as w (w.id)}
      <div class="grid-stack-item board-item" data-id={w.id} use:gridItem>
        <div class="grid-stack-item-content">
          {#if editMode}
            <div class="w-edit-bar">
              <button class="w-edit-btn" title="Configure" onclick={() => onConfigure(w.id)}><Settings2 /></button>
              <button class="w-edit-btn danger" title="Remove" onclick={() => onRemove(w.id)}><X /></button>
            </div>
          {/if}
          <WidgetHost widget={w} {onOptionsChange} />
        </div>
      </div>
    {/each}
  </div>
</div>
